// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: proto/order.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "order";

export interface CreateOrderRequest {
  userId: string;
  orderDetails: CreateOrderRequest_RequestOrder | undefined;
}

export interface CreateOrderRequest_RequestOrder {
  productId: string;
  qty: number;
  unitPrice: number;
}

export interface CreateOrderResponse {
  productId: string;
  qty: number;
  unitPrice: number;
  totalPrice: number;
  createdAt: string;
  orderId: string;
}

export interface GetOrderRequest {
  userId: string;
}

export interface GetOrderResponse {
  orders: GetOrderResponse_OrderEntity[];
}

export interface GetOrderResponse_OrderEntity {
  productId: string;
  qty: number;
  unitPrice: number;
  totalPrice: number;
  createdAt: string;
  updatedAt: string;
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  createOrder(request: CreateOrderRequest, metadata?: Metadata): Observable<CreateOrderResponse>;

  getOrders(request: GetOrderRequest, metadata?: Metadata): Observable<GetOrderResponse>;
}

export interface OrderServiceController {
  createOrder(
    request: CreateOrderRequest,
    metadata?: Metadata,
  ): Promise<CreateOrderResponse> | Observable<CreateOrderResponse> | CreateOrderResponse;

  getOrders(
    request: GetOrderRequest,
    metadata?: Metadata,
  ): Promise<GetOrderResponse> | Observable<GetOrderResponse> | GetOrderResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrders"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
