// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: proto/user.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface CreateUserRequest {
  email: string;
  name: string;
  pwd: string;
}

export interface CreateUserResponse {
  email: string;
  name: string;
  userId: string;
  orders: CreateUserResponse_ResponseOrder[];
}

export interface CreateUserResponse_ResponseOrder {
  productId: string;
  qty: number;
  unitPrice: number;
  totalPrice: number;
  createdAt: string;
  orderId: string;
}

export interface GetUserRequest {
  userId: string;
  pwd?: string | undefined;
}

export interface LoginResponse {
  token: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  createUser(request: CreateUserRequest, metadata?: Metadata): Observable<CreateUserResponse>;

  getUsers(request: GetUserRequest, metadata?: Metadata): Observable<CreateUserResponse>;

  getUser(request: GetUserRequest, metadata?: Metadata): Observable<CreateUserResponse>;

  login(request: GetUserRequest, metadata?: Metadata): Observable<LoginResponse>;
}

export interface UserServiceController {
  createUser(
    request: CreateUserRequest,
    metadata?: Metadata,
  ): Promise<CreateUserResponse> | Observable<CreateUserResponse> | CreateUserResponse;

  getUsers(
    request: GetUserRequest,
    metadata?: Metadata,
  ): Promise<CreateUserResponse> | Observable<CreateUserResponse> | CreateUserResponse;

  getUser(
    request: GetUserRequest,
    metadata?: Metadata,
  ): Promise<CreateUserResponse> | Observable<CreateUserResponse> | CreateUserResponse;

  login(
    request: GetUserRequest,
    metadata?: Metadata,
  ): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "getUsers", "getUser", "login"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
